apiVersion: v2
type: application
version: 1.0.0
appVersion: 1.0.0
description: A Helm chart for the deployment of multi-user JupyterHUB
name: jupyterhub
icon: https://xrootd.slac.stanford.edu/images/jupyterhub.png
maintainers:
  - name: marcoverl
    email: verlato@infn.it
home: https://github.com/marcoverl/helm-charts/sources/jupyterhub/
